version: '3'
services:
  # Container for Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - "./app:/var/www/html/app"
      - "./config:/var/www/html/config"
      - "./database:/var/www/html/database"
      - "./resources:/var/www/html/resources"
      - "./routes:/var/www/html/routes"
      - "./tests:/var/www/html/tests"
      - "./composer.json:/var/www/html/composer.json"
      - "./composer.lock:/var/www/html/composer.lock"
    ports:
      - "80:8000"
    environment:
      - "DB_HOST=dbbuzzvel"
      - "DB_PORT=3306"
      - "DB_DATABASE=buzzveldb"
      - "DB_USERNAME=buzzvelroot"
      - "DB_PASSWORD=buzzvelsecret132"
    command: bash -c "composer install --no-interaction \
      && php artisan key:generate \
      && php artisan config:cache \
      && php artisan route:cache \
      && php artisan view:cache \
      && chmod -R 777 storage \
      && chown -R www-data:www-data /var/www/html/storage \
      && php-fpm"
    depends_on:
      - dbbuzzvel
    networks:
      - buzzvel_net

  # Container for MariaDB
  dbbuzzvel:
    image: mariadb:10.6
    restart: always
    ports:
      - "3313:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=buzzveldb
      - MYSQL_USER=buzzvelroot
      - MYSQL_PASSWORD=buzzvelsecret132
    networks:
      - buzzvel_net

volumes:
  buzzvel-backend:

networks:
  buzzvel_net:
