# PHP Container
FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# work folder
WORKDIR /var/www/html

# Copy the Laravel source code into the container
COPY . .

# Start the PHP web server
CMD ["php", "artisan", "serve", "--host=0.0.0.0"]
